server:
  port: 8080
  servlet:
    context-path: /employ
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/user_db
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
jwt:
  signerKey: "UWOG67IDTlxApTrrn3ukTybaTHxvUyCuQ2FjMcTeRclpqNiPe9Yr3Fyt1j8zlvjn"
